### PR TITLE
🌏 Huber Regression Algorithm 📜 to ML/Algorithms/Regressions Repository

### PR DESCRIPTION
**Pull request by UTSAVS26**
## Issue: [Feature] --> Add Huber Regression Algorithm to the ML/Algorithms/Regressions Repository #11

<hr>

**This pull request aims to enhance the regression models available in the ML/Algorithms/Regressions repository by adding an implementation of the Huber Regression algorithm. Huber Regression is a robust linear regression technique that balances the characteristics of least squares and least absolute deviations, making it less sensitive to outliers.**

**The following tasks have been completed as part of this implementation:**
- Developed a new file named HuberRegression.py containing the Huber Regression algorithm.
- Created unit tests for the Huber Regression in test_HuberRegression.py.
- Updated the README.md file to include:
    1. Usage instructions
    2. Explanation of parameters
    3. Installation guide
    4. Information about running tests

The implementation has been tested locally to verify correctness and functionality. Unit tests have been added to ensure the robustness of the code.

This enhancement will provide a more comprehensive set of regression tools for users, enriching their machine learning toolkit.

I would appreciate it if you could assign this issue to me under SSOC'24. I am looking forward to contributing to this directory with the necessary Python programs.

### CODE REVIEW

**Comment by UTSAVS26** [comment]
Hi @Avdhesh-Varshney sir, please look into this PR and tell me if any change is required?

**Comment by Avdhesh-Varshney** [comment]
@UTSAVS26 join the discord server as i will creating a meeting for this project movement discussion today.

**Comment by UTSAVS26** [comment]
Hi @Avdhesh-Varshney I am on the discord channel of this project, what will the timings of the meeting?

**Review by Avdhesh-Varshney — APPROVED** [review]
@UTSAVS26 PR Approved 🎉

**Pull request merged**
