### PR TITLE
Issue Resolved Body Fat Prediction Model #38

### PR DESCRIPTION
**Pull request by vishalmaurya850**
Closes: 

- **Title** : Body Fat Prediction Model
- **Name:** <!Vishal Maurya>
- **Idenitfy yourself:** <!SSOC 24>

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

### Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/AI-Code/blob/main/README.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/AI-Code/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@vishalmaurya850 this is not a code contribution. This is for guidance for the project i.e. how the beginner can approach the machine learning projects. You can see this project for an reference. [link](https://github.com/Avdhesh-Varshney/AI-Code/tree/main/Pre-Processing/Projects/bangladesh_premier_league_analysis).

**Comment by vishalmaurya850** [comment]
I have to create a Readme file for that??

**Comment by vishalmaurya850** [comment]
Now merge the file

**Comment by Avdhesh-Varshney** [comment]
@vishalmaurya850 can't approve. Properly read the guidelines for project addition.

**Pull request closed without merging**
